### ISSUE TITLE
add reducers for lazy loaded modules

### ISSUE THREAD

**Issue by maku** [InfomediaLtd/angular2-redux-example#11]
Is it possible to add reducers at runtime (e.g. for lazy loading)?

**Comment by rubyboy** [comment]
@maku seems more like a pure redux question :)
Does this help? http://stackoverflow.com/questions/32968016/how-to-dynamically-load-reducers-for-code-splitting-in-a-redux-application

**Comment by maku** [comment]
You are right, thank you
