### ISSUE TITLE
Demo seems to be broken

### ISSUE THREAD

**Issue by Cyberdada** [InfomediaLtd/angular2-redux-example#6]
Hi, 
when running 
 http://angular2-redux-example.surge.sh 
in Chrome I get 
EXCEPTION: Error during instantiation of AppStore! (AdminComponent -> AppStore).BrowserDomAdapter.logError @ index.min.js:6
index.min.js:6 ORIGINAL EXCEPTION: TypeError: window.devToolsExtension is not a function

br 
Magnus

**Comment by rubyboy** [comment]
Hi @Cyberdada . Thanks for reporting this problem. I see it's an old version that had a problem when running in a browser without the Redux dev tools installed.
I've deployed the latest version and it should now work well.
Let me know if it's still not working for any reason.
Thanks again.
Ruby
