### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by divined** [InfomediaLtd/angular2-redux-example#7]
node_modules/angular2-redux/dist/app-store-factory.ts(2,70): error TS2307: Cannot find module 'redux'.
node_modules/angular2-redux/dist/app-store-factory.ts(3,34): error TS2307: Cannot find module 'redux-thunk'.

**Comment by rubyboy** [comment]
Try `npm install` and then `live-server``.

**Comment by divined** [comment]
Sory, i make mistake with location of issue, it is for main thread: https://github.com/InfomediaLtd/angular2-redux
