### ISSUE TITLE
Hi old friend... any luck with rc.x?

### ISSUE THREAD

**Issue by born2net** [InfomediaLtd/angular2-redux-example#8]
Hi old friend... any luck with rc.x?
I had spent so far 5 hours and got some progress but still has issues with loading everything in jspm version 0.17, wondering if you had any luck with ng2 rc.x, they broke alot of things :/

regards

Sean

**Comment by born2net** [comment]
FYI this will come handy: https://github.com/kiswa/angular2-base
got me pretty far

**Comment by rubyboy** [comment]
Hi mate. Great hearing from you!

No, I haven't had a chance to update all our projects yet. I just finished upgrading them all to the latest beta last week :(
I saw all these changes on the NG-Conf talks and wondered how easy it would be to upgrade. I was hoping it's just a matter of importing different modules, instead of a single one. I think I'll spend Sunday doing that so I'll let you know. Thanks for the link - let me know if you've got more tips to make it easy.

BTW, I still have a problem running tests with PhantomJS and JSPM. I've switched to Chrome in the meanwhile, but would like to tackle that as well next week.

**Comment by born2net** [comment]
tx, yes well some of the tips I can are:
. no more /... in sub routes (removed all dots)
. follow the include in the link: https://github.com/kiswa/angular2-base for all ng2 modules
. use find to search and replace all files

```
find ./ -type f -name "*.ts" -exec sed -i -e 's/angular2\/core/@angular\/core/g' {} \;
find ./ -type f -name "*.ts" -exec sed -i -e 's/angular2\/compiler/@angular\/compiler/g' {} \;
find ./ -type f -name "*.ts" -exec sed -i -e 's/angular2\/router/@angular\/router/g' {} \;
find ./ -type f -name "*.ts" -exec sed -i -e 's/angular2\/common/@angular\/common/g' {} \;
find ./ -type f -name "*.ts" -exec sed -i -e 's/angular2\/http/@angular\/http/g' {} \;
```

these are the mappings

```
angular2/core -> @angular/core
angular2/compiler -> @angular/compiler
angular2/common -> @angular/common
angular2/platform/browser -> @angular/platform-browser (applications with precompiled templates) + @angular/platform-browser-dynamic (applications that compile templates on the fly)
angular2/platform/server -> @angular/platform-server
angular2/testing -> @angular/core/testing (it/describe/..) + @angular/compiler/testing (TestComponentBuilder) + @angular/platform-browser/testing
angular2/upgrade -> @angular/upgrade
angular2/http -> @angular/http
angular2/router -> @angular/router-deprecated (snapshot of the component router from beta.17 for backwards compatibility)
new package: @angular/router - component router with several breaking changes
```

and router changes:

```
RouterLink -> ROUTER_DIRECTIVES
RouteConfig -> Routes
RouteParams -> RouteSegment
```

RouteSegment has a different interface, use getParam(string) instead of get(string)
import {BrowserDomAdapter} from '@angular/platform-browser/src/browser/browser_adapter';

and had to

```
jspm install angular-core=npm:@angular/core
jspm install angular-compiler=npm:@angular/compiler
jspm install angular-common=npm:@angular/common
jspm install angular-platform-browser=npm:@angular/platform-browser
jspm install angular-platform-browser-dynamic=npm:@angular/platform-browser-dynamic
jspm install http=npm:@angular/http
jspm install router=npm:@angular/router
```

regards

still some things are not working for me, will tackle tomorrow...

**Comment by rubyboy** [comment]
@born2net I've updated most of the public projects to angular2-rc1. It was a monumental effort, going through all repositories and fixing them. I can't say I'm full of love for them right now for getting all of this done so late in the game :(

I still have two open issues to deal with:
1. I still couldn't figure out how to run tests with JSPM and ng2-rc1. Something is missing there to get it to run properly without errors. If you have tips or managed to solve it I'd love to hear!
2. I left the router using the old "router-deprecated". I tried using the new one, but after spending too much time on it I figured I'd come back to it once they officially announce that it's public with sample code.

**Comment by born2net** [comment]
totally agree, not very happy either... I don't use testing so I dont have that issue, and I did move to the new router but I am missing a lot of functionality right now so my router is not filling my needs yet :/

**Comment by born2net** [comment]
hello again,
so seems like jspm is really not happy with rc.6
they changed everything around with systemjs:

https://github.com/angular/quickstart/blob/3b7452cc444c49c139ea39523ced0468c2362c16/systemjs.config.js#L17-L34

wondering if you have any experience applying the changes to rc.6?

regards

Sean.
