### ISSUE TITLE
pleeeease update to rc.6...

### ISSUE THREAD

**Issue by born2net** [InfomediaLtd/angular2-redux-example#9]
pleeeease update to rc.6...

tx

Sean

**Comment by rubyboy** [comment]
I think I'll wait for the final release, given that it's very soon. I'm tired from all the changes with every release :(
Did you end up figuring out the JSPM issue with RC6? I assume I'll be dealing with it soon...

**Comment by born2net** [comment]
yes figured it out... they made a bunch of modules private so they didnt load... glad I am at rc.6 as its final.. hoping =D

**Comment by born2net** [comment]
yes figured it out... they made a bunch of modules private so they didnt load... glad I am at rc.6 as its final.. hoping =D

**Comment by born2net** [comment]
more things to tackle... with release 2.0 you can no longer jspm bundle the application, I am getting an error on the minifaction process and I think it has something to do with how everything moved to ngModule. At this point I am thinking of moving to webpack as I can not figure this one out and there is almost no jspm support on the web for ng2.

**Comment by rubyboy** [comment]
I'm going to update all my projects soon so I'll need to decide as well. It feels like all bets are going on Webpack and the CLI, so maybe that's the right way to go now. Such a shame - I do love JSPM and hope it had more traction and stability.
What are your thoughts about the CLI? Given that it's based on Webpack would that be a good default place to start? Is it light enough?

**Comment by born2net** [comment]
so I did find a solution to my problem, posted here:
http://stackoverflow.com/questions/39535697/due-to-changes-in-angular-2-rc-6-jspm-bundling-no-longer-works

so I spent a long time thinking about how to move forward and this is what I came up with.

. no point to move to webpack as most likely ng-cli will be a fork of webpack with a ng2 twist so swithcing to webpack now will not really solve any issues. In fact, I tried webpack and found out there are issues with breakpoints in WebStorm. So moving to Webpack now will just introduce more noise.

. no point of moving to ng-cli for now. It does not support hot-reload yet, it will most likely change drastically in the next 3-4 months with breaking changes (again), and there isn't even yet a way to easly fork from github a ng-cli based project. An ng-cli based project on github means you have to include node_modules and 3rd party modules (since the ng-cli brings in a lot of custom stuff with it inside the node_modules which are not present in packages.json).

. jspm works perfectly right now.

so the bottom best thing is to stick with jspm for now. eventually I will migrate to ng-cli but only when it is fully features with support for AOT, hot-reload, easily host hostable on github and has good support for plugins.

regards

Sean

**Comment by born2net** [comment]
may be wrong on github hosting as this project seems to have done it:
https://github.com/hdjirdeh/angular2-hn

so I may try and update one of my projects to ng-cli and see how far I get

**Comment by rubyboy** [comment]
Cool, thanks for the info and the JSPM solution! I'll give it a try very soon.
I'm glad JSPM still works. I haven't yet made up my mind on moving to Webpack. JSPM is just so much easier and provides better dependency management, IMO. I'll update my projects and hopefully be able to stick with it for a little longer. A bit worrying that v17 is so long in the making, though...

**Comment by born2net** [comment]
agreed on v17, discouraging!!!!
I posted support Q's and got very little help from the jspm community. 
seems like all jspm users are into react! blaaaaa....
